spring.application.name=webserver

# SQLite — шлях до файлу бази даних
spring.datasource.url=jdbc:sqlite:D:/Coursework/RestManager/restaurant.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate діалект для SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# Показувати SQL запити в консолі
spring.jpa.show-sql=true

# Порт сервера
server.port=8080

# Кодування
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true

spring.jpa.properties.hibernate.connection.provider_disables_autocommit=false
spring.datasource.hikari.connection-init-sql=PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
spring.jpa.properties.hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
spring.datasource.hikari.auto-commit=true
spring.jpa.open-in-view=false